services:
  traefik:
    image: traefik:3.4
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
      - docker_socket
    ports:
      - "80:80"     # Default HTTP
      - "443:443"   # Default HTTPS
    volumes:
      - /docker/traefik/certs:/certs
      - /docker/traefik/files:/files
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`proxy.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.tls.certresolver=main"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${API_USERS}"
      - "traefik.enable=true"
    command:
      - "--providers.docker"
      - "--providers.docker.endpoint=tcp://docker_socket_proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.file.directory=/files"
      - "--providers.file.watch=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entryPoints.https.http.tls.certresolver=main"
      - "--entryPoints.https.http.tls.domains[0].main=${DOMAIN}"
      - "--entryPoints.https.http.tls.domains[0].sans=*.${DOMAIN}"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.main.acme.email=${EMAIL}"
      - "--certificatesresolvers.main.acme.storage=/certs/acme.json"
      - "--certificatesresolvers.main.acme.dnschallenge.provider=ovh"
      - "--api.dashboard"

  docker_socket_proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker_socket_proxy
    restart: unless-stopped
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - TASKS=1
    networks:
      - docker_socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
        - proxy
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls.certresolver=main"
      - "traefik.enable=true"

networks:
  proxy:
    name: proxy
    enable_ipv6: true
  docker_socket:
    name: docker_socket
